## Exercise 3. Get the nouns in the last 10 sentences from Trump's speech and find the nouns divided by sentencens. Use SpaCy.

Please use Python list features to get the last 10 sentences and display nouns from it.

In [3]:
import spacy
file = open("trump.txt", "r",encoding='utf-8')
trump = file.read()

### here comes your code
nlp = spacy.load("en_core_web_sm")
document = nlp(trump)
sentences = list(document.sents)[-10:]
nouns = []
for sentence in sentences:
    nouns.append([token.text for token in sentence if token.pos_ == "NOUN"])
print(nouns)


[['vision', 'years', 'freedom', 'tonight', 'chapter', 'greatness'], ['time', 'thinking'], ['time', 'fights'], ['courage', 'dreams', 'hearts', 'bravery', 'hopes', 'souls', 'confidence', 'hopes', 'dreams', 'action'], ['aspirations', 'fears', 'future', 'failures', 'past', 'vision', 'doubts'], ['citizens', 'renewal', 'spirit'], ['Members', 'things', 'country'], ['tonight', 'moment'], ['yourselves', 'future'], []]


## Exercise 4. Build your own Bag Of Words implementation using tokenizer created before

You need to implement following methods:

- ``fit_transform`` - gets a list of strings and returns matrix with it's BoW representation
- ``get_features_names`` - returns list of words corresponding to columns in BoW


In [4]:
import numpy as np
import spacy

class BagOfWords:
    """Basic BoW implementation."""

    def __init__(self):
        self.__nlp = spacy.load("en_core_web_sm", disable=["parser", "ner"])
        self.__feature_names = []

    def __tokenize(self, text: str) -> list:
        doc = self.__nlp(text.lower())
        return [token.lemma_ for token in doc if not token.is_stop and not token.is_punct]

    def fit_transform(self, corpus: list):

        tokenized_docs = [self.__tokenize(doc) for doc in corpus]

        vocabulary = sorted(set(token for doc in tokenized_docs for token in doc))
        self.__feature_names = vocabulary

        matrix = np.zeros((len(corpus), len(vocabulary)), dtype=int)

        for i, tokens in enumerate(tokenized_docs):
            for token in tokens:
                j = vocabulary.index(token)
                matrix[i][j] += 1

        return matrix


    def get_feature_names(self) -> list:
        """Return words corresponding to columns of matrix.
        """
        return self.__feature_names

corpus = [
     'Bag Of Words is based on counting',
     'words occurences throughout multiple documents.',
     'This is the third document.',
     'As you can see most of the words occur only once.',
     'This gives us a pretty sparse matrix, see below. Really, see below',
]

vectorizer = BagOfWords()

X = vectorizer.fit_transform(corpus)
print(X)

vectorizer.get_feature_names()
len(vectorizer.get_feature_names())

[[1 1 1 0 0 0 0 0 0 0 0 1]
 [0 0 0 1 0 0 1 0 1 0 0 1]
 [0 0 0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 1]
 [0 0 0 0 1 1 0 0 0 1 1 0]]


12